version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: taxi-mysql
    restart: always
    environment:
      MYSQL_DATABASE: taxi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./taxi.sql:/docker-entrypoint-initdb.d/taxi.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: taxi-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taxi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data: 